// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaaroogbsvuyqnrkyboy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhYXJvb2dic3Z1eXFucmt5Ym95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzOTU2NTMsImV4cCI6MjA3Njk3MTY1M30.9xQ9AZ1XgpkqfGgnyNYepvvd8FlXxq3NvVtKdlg32WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});